# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages + Other

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  # Configuration for the build
  RUBY_VERSION: 3.2 # Ruby version
  OTHER_HOSTING_URL: "https://githubpages-test.oit.gatech.edu" # URL for Other Hosting (e.g., "https://example.com")
  OTHER_HOSTING_BASEURL: "" # Base URL for Other Hosting (e.g., "/blog")
  OTHER_HOSTING_BRANCH: "other" # Deployment branch for Other Hosting build
  # Required environment variables for Jekyll + example `mmistakes/minimal-mistakes` theme
  JEKYLL_ENV: production
  JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JEKYLL_BUILD_REVISION: ${{ github.sha }}
  PAGES_REPO_NWO: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
        id: setup-ghpages
        uses: actions/configure-pages@v5
      - name: Build Jekyll for GitHub Pages
        run: |
          bundle exec jekyll build --baseurl "${{ steps.setup-ghpages.outputs.base_path }}"
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Build Jekyll for Other Hosting
        run: |
          echo "url: ${{ env.OTHER_HOSTING_URL }}" >> _other-url.yml
          bundle exec jekyll build --baseurl "${{ env.OTHER_HOSTING_BASEURL }}" --config _config.yml,_other-url.yml
      - name: Archive Other Hosting build files
        # Create a tarball of the Jekyll _site/ contents
        run: |
          tar -czvf other-hosting.tar -C _site .
      - name: Upload Other Hosting artifact
        uses: actions/upload-artifact@v4
        with:
          name: other-hosting
          path: other-hosting.tar
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  # Deploy for GitHub Pages
  deploy-ghpages:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment-ghpages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment-ghpages
        uses: actions/deploy-pages@v4

  # Deploy for Other Hosting
  deploy-other:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Prepare Other Hosting branch
        run: |
          git rm -rf .
          git clean -fdx
          git switch --orphan "${{ env.OTHER_HOSTING_BRANCH }}" || git switch "${{ env.OTHER_HOSTING_BRANCH }}"
      - name: Download Other Hosting artifact
        uses: actions/download-artifact@v5
        with:
          name: other-hosting
      - name: Extract Other Hosting build files
        run: |
          tar -xvf other-hosting.tar
          rm -f other-hosting.tar
      - name: Commit and push Other Hosting build files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy commit: ${{ env.JEKYLL_BUILD_REVISION }}" --author="${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>" || echo "No changes to commit"
          git push --force -u origin "${{ env.OTHER_HOSTING_BRANCH }}"